Admin Refresh
eventespresso/event-espresso-core pull request #3719
Opened 2022-02-14 23:02 UTC by tn3rb

This is some work I've been picking at for awhile to update the EE admin UI to better match with the changes in EDTR.

It's mostly cosmetic, but there are a few structural/layout tweaks as well, but those have been done in a backwards compatible manner as can be seen by looking at https://barista.eventespresso.com/ which has most EE plugins running.

2022-02-15 17:43 UTC, knazart requested changes
Found a couple but minor syntax errors and had a few things pointed out. 

Otherwise looks 👍

2022-02-15 17:43 UTC, knazart commented on admin_pages/events/Events_Admin_List_Table.class.php
> +            // 'status'          => '',
```suggestion
```

2022-02-15 17:43 UTC, knazart commented on admin_pages/events/Events_Admin_List_Table.class.php
> +        $content .= $this->column_name($event, false);;
```suggestion
        $content .= $this->column_name($event, false);
```

2022-02-15 17:43 UTC, knazart commented on admin_pages/events/Events_Admin_List_Table.class.php
> +        $content = EEM_Ticket::instance()->sum(array(array('Datetime.EVT_ID' => $event->ID())), 'TKT_sold');
```suggestion
        $content = EEM_Ticket::instance()->sum([['Datetime.EVT_ID' => $event->ID()]], 'TKT_sold');
```

2022-02-15 17:43 UTC, knazart commented on admin_pages/registrations/EE_Registrations_List_Table.class.php
> +        $edit_link_url  = EE_Admin_Page::add_query_args_and_nonce(
```suggestion
        $attendee       = $registration->attendee();
        $edit_link_url  = EE_Admin_Page::add_query_args_and_nonce(
```

2022-02-15 17:43 UTC, knazart commented on admin_pages/registrations/EE_Registrations_List_Table.class.php
> +            $actions['trash'] = '<a class="ee-aria-tooltip" href="'
```suggestion
            $action['action'] = 'trash_registrations';
            $trash_link_url   = EE_Admin_Page::add_query_args_and_nonce(
                $action,
                REG_ADMIN_URL
            );
            $actions['trash'] = '<a class="ee-aria-tooltip" href="'
```

2022-02-15 17:43 UTC, knazart commented on admin_pages/registrations/EE_Registrations_List_Table.class.php
> +                $restore_link_url    = EE_Admin_Page::add_query_args_and_nonce(
```suggestion
                $action['action']   = 'restore_registrations';
                $restore_link_url   = EE_Admin_Page::add_query_args_and_nonce(
```

2022-02-15 17:43 UTC, knazart commented on admin_pages/registrations/EE_Registrations_List_Table.class.php
> +                $delete_link_url    = EE_Admin_Page::add_query_args_and_nonce(
```suggestion
                $delete_link_url   = EE_Admin_Page::add_query_args_and_nonce(
```

2022-02-15 17:43 UTC, knazart commented on admin_pages/registrations/EE_Registrations_List_Table.class.php
> +        //             . '</span>';
```suggestion
```

2022-02-15 17:43 UTC, knazart commented on admin_pages/registrations/assets/espresso_registrations_admin.css
> +    padding: 5px 20px 5px 20px;;
```suggestion
    padding: 5px 20px 5px 20px;
```

2022-02-15 17:43 UTC, knazart commented on caffeinated/admin/extend/registrations/EE_Event_Registrations_List_Table.class.php
> +        // $name_link               .= '</span>';
```suggestion
```

2022-02-15 17:47 UTC, tn3rb commented on admin_pages/transactions/Transactions_Admin_Page.core.php
> +            $content .= implode('', $actions);
nope totally unnecessary with modern css.  we used to have to add extra markup in order to achieve specific layouts, but now with things like flexbox and grid it's totally unnecessary.

2022-02-15 17:57 UTC, tn3rb commented on admin_pages/messages/Messages_Template_List_Table.class.php
> +        // $c_label           = $item->context_label();
oh i think it just looked like it was removed in the diff, but that's still used on line 362

2022-02-25 21:57 UTC, garthkoyle commented
* [ ] Can the Add New Event button be blue instead of green? I don’t think we use a green action button elsewhere (or at least I haven’t noticed).
* [ ] https://github.com/eventespresso/event-espresso-core/issues/3742
* [ ] The Transactions > `Apply Discount Code` button could use some love.
* [ ] In Messages > Default Templates or Custom Templates, can we make the Recipients column wider, and narrow down the Description column of the Messages Templates view? 99.999% of the time we're looking to click the correct message context, not read the description.
* [ ] The Messages Templates editor Update Actions button style needs some love:
* [ ] The Venue “Update Venue” `Move to Trash` button needs some love
* [ ] The Promotions `Save and Close` button needs some love
* [ ] The “People Admin” `Add Person` form needs some love with the Last Name:
https://www.screencast.com/t/cXM4TVPK
* [ ] The Save Person Record `Move to Trash` button needs some love

2022-03-08 17:55 UTC, closed without merging

2022-03-08 18:01 UTC, tn3rb commented on admin_pages/messages/Messages_Template_List_Table.class.php
> +        // $c_label           = $item->context_label();
oops... read your comment wrong... ya this can be (and has been) removed