Escaped some variables.
eventespresso/event-espresso-core pull request #3739
Opened 2022-02-23 14:59 UTC by hoseinrafiei

## Problem this Pull Request solves
It's a starter for https://github.com/eventespresso/event-espresso-core/issues/3738 issue.

## How has this been tested
I did full E2E tests for the upcoming event widget in both of classic editor and block editor.

Also I changed some codes on a shortcode for thank you page which I think is deprecated and have no use at the moment.

## Screenshots for Tests

<img width="709" alt="Screen Shot 2022-02-23 at 18 01 25" src="https://user-images.githubusercontent.com/29144542/155344888-055291ee-8cf0-4e37-91f0-1dcfcf11f740.png">

<img width="480" alt="Screen Shot 2022-02-23 at 18 00 52" src="https://user-images.githubusercontent.com/29144542/155344827-f453a9b3-f7b9-4b62-99ce-9cf3659a186c.png">

2022-02-23 15:10 UTC, hoseinrafiei commented
@tn3rb 

I investigated the ticket and there are lots of jobs to be done for this so I split the task to following 2 phases.

### Escaping Phase
I found about 800 variables that should be checked for escaping in following directories. I will check and fix them part by part and will create separate PRs for them.

admin_pages (188)
caffeinated (330)
core (120)
modules (110)
public (19)
shortcodes (5)
widgets (21)

Other directories are ignored either due to development purposes or zero variables to get escaped.

### wp_kses Phase
After the first phase, I will start checking the remained variables to apply `wp_kses` function. Right now there are lots of variables that should be checked but after doing the first phase, there will be much less to for investigation.

I will improve the `core/services/request/sanitizers/AllowedTags.php` since there are many more tags and attributes that should be added. I may add some functions to get the tags based on context as you suggested.

Please let me know your thoughts for this PR and also for the whole plan. Your feedback will be a great help.

2022-02-23 16:29 UTC, tn3rb requested changes
looks great but need to swap out of of the escape functions being used

2022-02-23 16:29 UTC, tn3rb commented on shortcodes/espresso_thank_you/templates/thank-you-page-transaction-details.template.php
> +                        <a href='<?php echo esc_url($SPCO_payment_options_url); ?>'>
`esc_url()` is fine for display, but for URLs that need to work, it's better to use `esc_url_raw()`

2022-02-23 16:29 UTC, tn3rb commented on shortcodes/espresso_thank_you/templates/thank-you-page-transaction-details.template.php
> +            <a href='<?php echo esc_url($SPCO_payment_options_url); ?>'><?php
```suggestion
            <a href='<?php echo esc_url_raw($SPCO_payment_options_url); ?>'><?php
```

2022-02-23 16:29 UTC, tn3rb commented on widgets/upcoming_events/EEW_Upcoming_Events.widget.php
> +        return parent::get_field_id($field_name);
👍🏻

2022-02-24 13:49 UTC, hoseinrafiei commented
> looks great but need to swap out of of the escape functions being used

Thanks @brent. I fixed those items, Please check it again.

2022-02-25 16:58 UTC, tn3rb approved these changes
yup looks great now, thnx 💯

2022-02-28 08:10 UTC, hoseinrafiei commented
@mohdshakeel Please check this branch and do an E2E test.
After that please inform me to merge the branch.

2022-02-28 11:14 UTC, mohdshakeel commented
I have tested the widget **Event Espresso Upcoming Events** . I picked each settings options one by one and nothing found any issue with its back-end settings and front-end display.
Front end is displaying perfect with each setting of widget.

![image](https://user-images.githubusercontent.com/1772444/155973381-e07d307c-6831-4969-bf13-4608b073f3ad.png)

2022-02-28 13:29 UTC, mohdshakeel reviewed
Can We use the **wp_get_attachment_image** function at **public/Espresso_Arabica_2014/content-espresso_events-thumbnail.php** to display the feature image? It may better in terms of speed optimization.

2022-03-01 18:34 UTC, tn3rb commented
> Can We use the wp_get_attachment_image function at public/Espresso_Arabica_2014/content-espresso_events-thumbnail.php to display the feature image? It may better in terms of speed optimization.

that would be addressed in a separate issue, but is not important atm as we will be migrating everything over to blocks at some point

2022-03-02 12:15 UTC, merged